
baseURL: https://wyb0.com/
languageCode: en-us
theme: smigle
title: Reber's Blog

paginate: 10 # 分页
summaryLength: 60 # 摘要长度
preserveTaxonomyNames: true # 保持分类的原始名字（false 会做转小写处理）
disablePathToLower: true # 是否禁止 URL Path 转小写
hasCJKLanguage: true # 自动检测是否包含中文/日文/韩文，建议设置为 true


menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 2
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 3
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 4
    - identifier: about
      name: About
      url: /about/
      weight: 5
    - identifier: friends
      name: Friends
      url: /friends/
      weight: 6

params:
  author: "Reber"
  subtitle: "只会一点点编程、只会一点点渗透"
  # dateFmt: "2006-01-02 15:04:05"
  dateFmt: "2006-01-02"
  abbrDateFmt: "01-02"
  brandIconFile: "img/logo.png"
  siteStartYear: "2015"
  customStylesheets: # Use to override theme styles, like logo size
    - "css/monokai-sublime.min.css"
    -  "css/style.css"
  customJavaScripts:
    - "js/jquery-3.6.0.min.js"
    - "js/highlight.min.js"
    - "js/style.js"
  social:
    - name: GitHub
      url: https://github.com/reber0?_blank
    - name: Weibo
      url: https://weibo.com/u/5819760166?_blank
  